Fix quasar dev server startup.
When running `yarn dev` I was seeing the error:

    TypeError: Merging undefined is not supported
	at mergeWithOptions (headway/services/frontend/www-app/node_modules/webpack-merge/dist/index.js:52:19)
	at merge (headway/services/frontend/www-app/node_modules/webpack-merge/dist/index.js:41:35)
	at headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/config-tools.js:78:9
	at Array.forEach (<anonymous>)
	at parseVitePlugins (headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/config-tools.js:25:11)
	at createViteConfig (headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/config-tools.js:148:10)
	at Object.vite (headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/modes/spa/spa-config.js:6:17)
	at SpaDevServer.#runVite (headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/modes/spa/spa-devserver.js:23:37)
	at headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/modes/spa/spa-devserver.js:14:39
	at headway/services/frontend/www-app/node_modules/@quasar/app-vite/lib/app-devserver.js:76:48

The plugin in question was enabled as part of:

    commit 562ffc2e3ba4ddc07ed50548339250b0db61c5eb
    Author: Ellen Poe <ellen@ellenhp.me>
    Date:   Sat Aug 27 22:39:47 2022 -0700

        Add geolocation and misc fixes

It's not clear from the commit what problem specifically this was
solving, but the plugin hasn't been updated in a while (6 months+), and
I don't observe any problems after removing it. Let's see how it goes!