Fix broken tests
Tests were broken since I introduced lodash ab9aa5a0e7fa2a20d27d7d0638dba6487019421c

    src/utils/Prefs.ts:2:25 - error TS7016: Could not find a declaration file for module 'lodash'. '/Users/mkirk/src/headwaymaps/headway
    /web/frontend/node_modules/lodash/lodash.js' implicitly has an 'any' type.
      Try `npm i --save-dev @types/lodash` if it exists or add a new declaration (.d.ts) file containing `declare module 'lodash';`

    > import { isEqual } from 'lodash';
                              ~~~~~~~~